### ISSUE TITLE
Upgrade Roadmap

### ISSUE THREAD

**Issue by chenshunliang** [kubegems/dashboard#433]
Our code upgrade plan，We will gradually go from vue2 to vue3, this will go through multiple processes, the plan will start in November and will continue for several months。

- [ ]  Upgrade vue2.x to vue2.7.x
- [ ]  Integrate vite3, remove webpack
- [ ]  Transform Options API to Composition API
- [ ]  Transform JS to TS
- [ ]  Upgrade vue2.7.x to vue3
- [ ]  Upgrade vuetify2.x to vuetify3.x
